name: infixedu
description: A new Flutter project.

publish_to: 'none'

version: 5.0.0+60


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  dio:
  equatable:
  file_picker:
  file_utils:
  flutter_bloc: ^8.0.1
  flutter_calendar_carousel:
  flutter_cupertino_date_picker_fork:
  flutter_local_notifications:
  flutter_webview_plugin:
  fluttertoast:
  http:
  open_file:
  path_provider:
  rxdart:
  scoped_model:
  shared_preferences:
  uuid:
  shimmer:
  fancy_shimmer_image:
  url_launcher:
  intl:
  flutter_overlay_loader:
  flutter_cache_manager:
  timeago:
  flutter_slidable:
  font_awesome_flutter:
  flutter_cached_pdfview: ^0.4.2
  provider:
  cached_network_image:
  flutter_inappwebview:
  ffi:
  firebase_core:
  firebase_messaging:
  flutter_dropdown_alert:
  edge_alerts:
  flutter_screenutil:
  flutter_widget_from_html:
  permission_handler:
  http_auth:
#  flutter_paystack:
#    git:
#      url: https://github.com/definitelyme/flutter_paystack.git
#      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01
  flutter_credit_card:
  carousel_slider:
  persistent_bottom_nav_bar:
#  device_info_plus:
  get: ^4.6.5
  google_fonts:
  badges:
#  stripe_sdk:
  flutter_portal:
  loading_more_list:
  logger:
  emoji_picker_flutter:
  flutter_easyloading:
  photo_view:
  better_player:
  flutter_staggered_animations:
  razorpay_flutter:
  pdf:
  khalti:
  reorderables:
    git: https://github.com/emran92/reorderables
  pusher_channels_flutter:
  image:
  image_picker:
  image_picker_android:
  dots_indicator: ^3.0.0
  flutter_image_compress:




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.11
  import_sorter: ^4.6.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/config/app_icon.jpg"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/config/splash_logo.png
  fullscreen: true
  color: "f7f7f7"


flutter:
  uses-material-design: true
  assets:
   - assets/config/
   - assets/images/
   - assets/locale/

fonts:
  - family: popins
    fonts:
      - asset: fonts/poppins_medium.ttf
        weight: 100
      - asset: fonts/poppins_bold.ttf
        weight: 200
      - asset: fonts/poppins_light.ttf
        weight: 300
      - asset: fonts/poppins_regular.ttf
        weight: 400
      - asset: fonts/poppins_semibold.ttf
        weight: 500