///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MealsModelData {
/*
{
  "id": 4,
  "title": "meat + banana",
  "subtitle": "nothing",
  "dateofmeal": "2023-05-11 00:00:00",
  "image": "1683685269.jpg",
  "created_at": "0000-00-00",
  "updated_at": "0000-00-00",
  "order_meal": 0
}
*/

  int id;
  String title;
  String subtitle;
  String dateofmeal;
  String image;
  String createdAt;
  String updatedAt;
  int orderMeal;

  MealsModelData({
    this.id,
    this.title,
    this.subtitle,
    this.dateofmeal,
    this.image,
    this.createdAt,
    this.updatedAt,
    this.orderMeal,
  });
  MealsModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    title = json['title']?.toString();
    subtitle = json['subtitle']?.toString();
    dateofmeal = json['dateofmeal']?.toString();
    image = json['image']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    orderMeal = json['order_meal']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['title'] = title;
    data['subtitle'] = subtitle;
    data['dateofmeal'] = dateofmeal;
    data['image'] = image;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['order_meal'] = orderMeal;
    return data;
  }
}

class MealsModel {
/*
{
  "data": [
    {
      "id": 4,
      "title": "meat + banana",
      "subtitle": "nothing",
      "dateofmeal": "2023-05-11 00:00:00",
      "image": "1683685269.jpg",
      "created_at": "0000-00-00",
      "updated_at": "0000-00-00",
      "order_meal": 0
    }
  ]
}
*/

  List<MealsModelData> data;

  MealsModel({
    this.data,
  });
  MealsModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MealsModelData>[];
      v.forEach((v) {
        arr0.add(MealsModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v.forEach((v) {
        arr0.add(v.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
